apiVersion: v1
kind: Pod
spec:
  containers:
  - name: buildah
    image: quay.io/containers/buildah:latest
    imagePullPolicy: "IfNotPresent"
    command:
    - cat
    tty: true
    volumeMounts:
      - mountPath: /var/run/docker.sock
        name: docker-sock
  - name: docker
    image: docker:latest
    imagePullPolicy: "IfNotPresent"
    command:
    - cat
    tty: true
    volumeMounts:
      - mountPath: /var/run/docker.sock
        name: docker-sock
  # - name: kubectl
  #   image: slw/ourkubectl:latest
  #   imagePullPolicy: "IfNotPresent"
  #   command:
  #   - cat
  #   tty: true
  #   volumeMounts:
  #     - mountPath: /var/run/docker.sock
  #       name: docker-sock
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock